version: "3.8"
services:
  portfoliob:
    build: .
    restart: always
    ports:
      - "80:80"
      - "5173:5173"
      - "8000:8000"
    links:
      - db
    depends_on:
      - db
    networks:
      networkwp:
        ipv4_address: 172.24.0.10
    volumes:
      - ./:/var/www/html:rwx
  db:
    image: mysql:8.0.32
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: portfoliob1234
      MYSQL_DATABASE: portfoliob
      MYSQL_USER: kingAlfy
      MYSQL_PASSWORD: portfoliob1234
    networks:
      networkwp:
        ipv4_address: 172.24.0.2
    volumes:
      - ./bbdd:/var/lib/mysql:rwx
  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    restart: always
    links:
      - db
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
    networks:
      networkwp:
        ipv4_address: 172.24.0.30
networks:
  networkwp:
    ipam:
      config:
        - subnet: 172.24.0.0/24